### ISSUE TITLE
Question about multiple room setup

### ISSUE THREAD

**Issue by jdkoelsch** [hipchat/redmine_hipchat#10]
My company has several projects going on at once, and I have started creating HipChat rooms for each project. I'd like to connect our Redmine project with it's corresponding HipChat room. However, it looks like this plugin only allows you to configure one room to be connected -- the HipChat plugin settings don't appear to be per project. Can you confirm that I'm understanding how to use the plugin correctly? If so, do you have any suggestions on how to set up our Redmine and HipChat so that all Redmine activity isn't being dumped into one HipChat room?

Thanks!

**Comment by powdahound** [comment]
I believe that's an accurate description of the current setup and agree that more flexibility would be nice. It's not something we have plans to add as we don't see much usage of this plugin, but if you have anyone to make the improvements we'd happy accept pull requests.

**Comment by mikeyhill** [comment]
What are the supported redmine versions for this plugin?

**Comment by vkotovv** [comment]
Will be glad to see multi-room settings. Did not have a chance to code in Ruby though..

**Comment by vkotovv** [comment]
@mikeyhell It works on 1.3, and it is stated that it supports Redmine 2.x

**Comment by biow0lf** [comment]
@powdahound I have add support for ability to set room per project. See PR #14.

@mikeyhell @vkotovv current plugin will not work with Redmine older then 2.0.0.

**Comment by powdahound** [comment]
Merged in @biow0lf's changes (thanks!) - so hopefully that works for you.

**Comment by vkotovv** [comment]
@biow0lf What do you mean by that? Your changes is not compatible with Redmine < 2.x? I use [this revision](https://github.com/hipchat/redmine_hipchat/commit/06ebb506f1f4289ecd34ed7c502d4307d2079774) and it works OK on my Redmine 1.3.0 installation.
