### ISSUE TITLE
Another 500 error

### ISSUE THREAD

**Issue by mikeyhill** [hipchat/redmine_hipchat#11]
Started GET "/settings/plugin/hipchat" for xx.xx.xx.xxx at Tue Jun 05 00:24:56 -0400 2012
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"hipchat"}
  Rendered settings/plugin.html.erb within layouts/admin (2.9ms)
Completed 500 Internal Server Error in 8ms

ActionView::Template::Error (Missing partial hipchat/settings with {:locale=>[:en], :handlers=>[:rsb, :rjs, :builder, :erb], :formats=>[:html]}. Searched in:
- "/usr/share/redmine/plugins/redmine_lightbox/app/views"
- "/usr/share/redmine/app/views"
  ):
  3: <div id="settings">
  4: <%= form_tag({:action => 'plugin'}) do %>
  5: <div class="box tabular">
  6: <%= render :partial => @partial, :locals => {:settings => @settings}%>
  7: </div>
  8: <%= submit_tag l(:button_apply) %>
  9: <% end %>
  app/views/settings/plugin.html.erb:6:in `_app_views_settings_plugin_html_erb___1182364635_70248745006360'
  app/views/settings/plugin.html.erb:4:in`_app_views_settings_plugin_html_erb___1182364635_70248745006360'

**Comment by powdahound** [comment]
No other reports of this issue. Going to assume it was something unique to your configuration.
