### ISSUE TITLE
Plugin installed failed.

### ISSUE THREAD

**Issue by doublechiang** [hipchat/redmine_hipchat#16]
When I installed this plugin on an existing Redmine installation 1.4.2. After install the plugin in with standard command, 

rake db:migrate_plugins RAILS_ENV=production

no plugin was displayed in the plugins page. 

So I installed a fresh copy of Bitnami Redmine 1.7.4 on this version, after I register with 

rake redmine:plugins:migrate RAILS_ENV=production

The hipchat plugins are displayed on the administration/plugin page.

Am I necessary to do the extra setting on version 1.4.2? or are there any other error？
I created an issue on the redmine.org, but they asked me to report the problem here.

http://www.redmine.org/issues/14058

**Comment by doublechiang** [comment]
Just found a bitnami redmine is also available, so I download it, and installed it, then install the plugin.
Everything goes fine.

**Comment by powdahound** [comment]
Was this reopened intentionally? Sounds like you fixed it.

**Comment by doublechiang** [comment]
Nop, sorry, I did not sovle it.
I installed a fresh copy of Redmine, it work.
But on my production redmine, it can not.

I close this issue accidentally, can you guide me how to debug and trace it?

The log I had is listed as following
------------------- cut here ----------------
ActionView::TemplateError (undefined method `hipchat_auth_token' for #Project:0x7fef31dd6418) on line #2 of vendor/plugins/redmine_hipchat/app/views/projects/_redmine_hipchat
1: <p>
2:   <%= form.text_field :hipchat_auth_token %>
3:   A token from <a href="https://www.hipchat.com/group_admin/api" target="_blank">your API tokens page</a>. Leave empty for use global settings.
4: </p>
5:

```
lib/redmine/views/labelled_form_builder.rb:31:in `text_field'
vendor/plugins/redmine_hipchat/app/views/projects/_redmine_hipchat.html.erb:2
lib/redmine/hook.rb:113:in `send'
lib/redmine/hook.rb:113:in `view_projects_form'
lib/redmine/hook.rb:63:in `send'
lib/redmine/hook.rb:63:in `call_hook'
lib/redmine/hook.rb:63:in `each'
lib/redmine/hook.rb:63:in `call_hook'
lib/redmine/hook.rb:60:in `tap'
lib/redmine/hook.rb:60:in `call_hook'
lib/redmine/hook.rb:146:in `call_hook'
app/views/projects/_form.html.erb:23
app/views/projects/_edit.html.erb:2
app/helpers/application_helper.rb:934:in `labelled_form_for'
app/views/projects/_edit.html.erb:1
app/views/common/_tabs.html.erb:24
app/views/common/_tabs.html.erb:23:in `each'
app/views/common/_tabs.html.erb:23
app/helpers/application_helper.rb:231:in `render_tabs'
app/views/projects/settings.html.erb:3
/usr/lib/ruby/1.8/phusion_passenger/rack/request_handler.rb:95:in `process_request'
/usr/lib/ruby/1.8/phusion_passenger/abstract_request_handler.rb:207:in `main_loop'
/usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:374:in `start_request_handler'
/usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:332:in `handle_spawn_application'
/usr/lib/ruby/1.8/phusion_passenger/utils.rb:184:in `safe_fork'
/usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:330:in `handle_spawn_application'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `__send__'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `main_loop'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:163:in `start'
/usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:209:in `start'
/usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:262:in `spawn_rails_application'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:126:in `lookup_or_add'
/usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:256:in `spawn_rails_application'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:80:in `synchronize'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
/usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:255:in `spawn_rails_application'
/usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:154:in `spawn_application'
/usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:287:in `handle_spawn_application'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `__send__'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `main_loop'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
/usr/lib/phusion_passenger/passenger-spawn-server:61
```

Rendering /usr/share/redmine-1.4-stable/public/500.html (500 Internal Server Error)

**Comment by powdahound** [comment]
Try the commit before this pull was merged in: https://github.com/hipchat/redmine_hipchat/pull/12. Or try upgrading to Redmine 2. :)

**Comment by doublechiang** [comment]
Thanks, after I upgrade my Redmine to 2.3, I can install the plugin now.
