### ISSUE TITLE
Allow only for a list of projects

### ISSUE THREAD

**Issue by trappist** [hipchat/redmine_hipchat#2]
We have dozens of projects.  Eventually a nice feature might be to allow for per-project room configurations, but our immediate problem would be solved if we could select which projects to enable notifications for.

**Comment by powdahound** [comment]
We're super busy right now so it's very unlikely we'll add this functionality anytime soon. If you or anyone else on your team has time to fork the project and add it we'd be happy to merge it back in for others to use.

**Comment by trappist** [comment]
Great, thanks for the quick response.  Busy here too but also highly motivated so we'll see what happens.

**Comment by powdahound** [comment]
Fixed by pull #3
