### ISSUE TITLE
Notifications for issues marked as private get posted to HipChat

### ISSUE THREAD

**Issue by Westhuyzen** [hipchat/redmine_hipchat#21]
Unfortunately this basically negates the private issue feature in Redmine if create/update messages get sent to the HipChat project room.

**Comment by elboletaire** [comment]
It should be a checkbox, I like the current behavior (my clients cannot access my HipChat rooms).

**Comment by Westhuyzen** [comment]
Redmine API supports this as of 2.6.0 http://www.redmine.org/issues/10914

**Comment by Westhuyzen** [comment]
Hipchat is no more.
