### ISSUE TITLE
Conflict with redmine backlog plugin

### ISSUE THREAD

**Issue by apatry** [hipchat/redmine_hipchat#9]
This plugin conflicts with the redmine backlog plugin which also stores its configuration view under `app/views/shared/_settings.html.erb`.

I was able to solve the problem by renaming `app/views/shared` by `app/views/hipchat` and applying the following modification in `init.rb`:

``` ruby
:partial => 'hipchat/settings'
```

**Comment by powdahound** [comment]
Cool, thanks for the heads up. If you have a pull request you can send I'd be happy to merge it in. Otherwise I'll try to get to it soon.
